"""Tests for SECRET_KEY validation in dependencies module."""

import logging
from unittest.mock import patch

import pytest


@pytest.fixture
def reset_dependencies_module():
    """Reset the dependencies module to allow re-importing with different SECRET_KEY values."""
    import sys

    # Remove the module from sys.modules to force re-import
    if "src.api.dependencies" in sys.modules:
        del sys.modules["src.api.dependencies"]
    yield
    # Clean up after test
    if "src.api.dependencies" in sys.modules:
        del sys.modules["src.api.dependencies"]


def test_validate_secret_key_default_value_warns(reset_dependencies_module, caplog):
    """Test that using default SECRET_KEY triggers a warning."""
    with patch.dict(
        "os.environ",
        {"SECRET_KEY": "your-secret-key-change-in-production"},  # pragma: allowlist secret
    ):
        with caplog.at_level(logging.WARNING):
            # Import will trigger validation
            import src.api.dependencies  # noqa: F401

            assert "SECURITY WARNING: Using default SECRET_KEY!" in caplog.text
            assert "python -c 'import secrets;" in caplog.text


def test_validate_secret_key_too_short_warns(reset_dependencies_module, caplog):
    """Test that a too-short SECRET_KEY triggers a warning."""
    with patch.dict("os.environ", {"SECRET_KEY": "short_key_123"}):  # pragma: allowlist secret
        with caplog.at_level(logging.WARNING):
            import src.api.dependencies  # noqa: F401

            assert "SECURITY WARNING: SECRET_KEY is too short" in caplog.text
            assert "Minimum recommended length is 32 characters" in caplog.text


def test_validate_secret_key_low_entropy_warns(reset_dependencies_module, caplog):
    """Test that a low-entropy SECRET_KEY triggers a warning."""
    # Key with only 5 unique characters repeated
    with patch.dict(
        "os.environ",
        {"SECRET_KEY": "aaaabbbbccccddddeeeeffffffffgggg"},  # pragma: allowlist secret
    ):
        with caplog.at_level(logging.WARNING):
            import src.api.dependencies  # noqa: F401

            assert "SECURITY WARNING: SECRET_KEY has low entropy" in caplog.text


def test_validate_secret_key_valid_no_warning(reset_dependencies_module, caplog):
    """Test that a strong SECRET_KEY does not trigger warnings."""
    # Strong key with 32+ chars and high entropy
    strong_key = "Kx7mP9nQ2rS5tU8vW1xY4zA6bC3dE0fG"  # pragma: allowlist secret
    with patch.dict("os.environ", {"SECRET_KEY": strong_key}):
        with caplog.at_level(logging.WARNING):
            import src.api.dependencies  # noqa: F401

            # Should have no WARNING level logs
            warnings = [record for record in caplog.records if record.levelname == "WARNING"]
            assert len(warnings) == 0


def test_validate_secret_key_urlsafe_token_format(reset_dependencies_module, caplog):
    """Test that a token generated by secrets.token_urlsafe(32) is valid."""
    import secrets

    token = secrets.token_urlsafe(32)
    with patch.dict("os.environ", {"SECRET_KEY": token}):
        with caplog.at_level(logging.WARNING):
            import src.api.dependencies  # noqa: F401

            warnings = [record for record in caplog.records if record.levelname == "WARNING"]
            assert len(warnings) == 0
