"""create trades table

Revision ID: 02b81a8386e8
Revises: b6ad8d407fac
Create Date: 2025-12-30 13:25:08.250175

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02b81a8386e8"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "b6ad8d407fac"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=10), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("pnl_percent", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("grid_level", sa.Integer(), nullable=True),
        sa.Column("entry_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trades_user_account", "trades", ["user_id", "account_type"], unique=False)
    op.create_index("idx_trades_user_closed", "trades", ["user_id", "closed_at"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index("idx_trades_user_closed", table_name="trades")
    op.drop_index("idx_trades_user_account", table_name="trades")
    op.drop_table("trades")
    # ### end Alembic commands ###
