"""create grid_configs table

Revision ID: 66a6855ef0ed
Revises: 90199c9f1c82
Create Date: 2026-01-01 21:06:05.695183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66a6855ef0ed"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "90199c9f1c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grid_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("spacing_type", sa.String(length=20), nullable=False),
        sa.Column("spacing_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("range_percent", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("max_total_orders", sa.Integer(), nullable=False),
        sa.Column("anchor_mode", sa.String(length=20), nullable=False),
        sa.Column("anchor_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="uq_grid_config_account"),
    )
    op.create_index(op.f("ix_grid_configs_account_id"), "grid_configs", ["account_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grid_configs_account_id"), table_name="grid_configs")
    op.drop_table("grid_configs")
    # ### end Alembic commands ###
