"""create bot_state table

Revision ID: 67e90c16057f
Revises: f8f729ea66bb
Create Date: 2025-12-30 14:38:23.059397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67e90c16057f"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "f8f729ea66bb"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("cycle_activated", sa.Boolean(), nullable=False),
        sa.Column("last_state", sa.String(length=20), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("last_state_change_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="uq_bot_state_account"),
    )
    op.create_index(op.f("ix_bot_state_account_id"), "bot_state", ["account_id"], unique=True)
    op.create_index(
        op.f("ix_tp_adjustments_trade_id"), "tp_adjustments", ["trade_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tp_adjustments_trade_id"), table_name="tp_adjustments")
    op.drop_index(op.f("ix_bot_state_account_id"), table_name="bot_state")
    op.drop_table("bot_state")
    # ### end Alembic commands ###
