"""create strategies table

Revision ID: 93dd60cd2374
Revises: 34ade06a4bbd
Create Date: 2026-01-07 14:18:41.839228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93dd60cd2374"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "34ade06a4bbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("order_size_usdt", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("margin_mode", sa.String(length=10), nullable=False),
        sa.Column("take_profit_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tp_dynamic_enabled", sa.Boolean(), nullable=False),
        sa.Column("tp_dynamic_base", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tp_dynamic_min", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tp_dynamic_max", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tp_dynamic_safety_margin", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tp_dynamic_check_interval", sa.Integer(), nullable=False),
        sa.Column("spacing_type", sa.String(length=20), nullable=False),
        sa.Column("spacing_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("range_percent", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("max_total_orders", sa.Integer(), nullable=False),
        sa.Column("anchor_mode", sa.String(length=20), nullable=False),
        sa.Column("anchor_threshold", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_strategies_account_active",
        "strategies",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(op.f("ix_strategies_account_id"), "strategies", ["account_id"], unique=False)
    op.drop_index(op.f("idx_activity_events_account_id"), table_name="activity_events")
    op.create_index(
        op.f("ix_activity_events_account_id"), "activity_events", ["account_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_events_account_id"), table_name="activity_events")
    op.create_index(
        op.f("idx_activity_events_account_id"), "activity_events", ["account_id"], unique=False
    )
    op.drop_index(op.f("ix_strategies_account_id"), table_name="strategies")
    op.drop_index(
        "ix_strategies_account_active",
        table_name="strategies",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("strategies")
    # ### end Alembic commands ###
