"""create trades table

Revision ID: a162c33f6eea
Revises: b6ad8d407fac
Create Date: 2025-12-30 13:33:22.376787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a162c33f6eea"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "b6ad8d407fac"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=100), nullable=True),
        sa.Column("exchange_tp_order_id", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("tp_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("tp_percent", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("pnl_percent", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("trading_fee", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("funding_fee", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("grid_level", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("filled_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_trades_account_closed", "trades", ["account_id", "closed_at"], unique=False
    )
    op.create_index("idx_trades_account_id", "trades", ["account_id"], unique=False)
    op.create_index("idx_trades_account_status", "trades", ["account_id", "status"], unique=False)
    op.create_index(
        "idx_trades_exchange_order",
        "trades",
        ["account_id", "exchange_order_id"],
        unique=True,
        postgresql_where=sa.text("exchange_order_id IS NOT NULL"),
    )
    op.create_index("idx_trades_status", "trades", ["status"], unique=False)
    op.create_index(op.f("ix_trades_account_id"), "trades", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_account_id"), table_name="trades")
    op.drop_index("idx_trades_status", table_name="trades")
    op.drop_index(
        "idx_trades_exchange_order",
        table_name="trades",
        postgresql_where=sa.text("exchange_order_id IS NOT NULL"),
    )
    op.drop_index("idx_trades_account_status", table_name="trades")
    op.drop_index("idx_trades_account_id", table_name="trades")
    op.drop_index("idx_trades_account_closed", table_name="trades")
    op.drop_table("trades")
    # ### end Alembic commands ###
