"""create_macd_filter_configs_table

Revision ID: bae863d9d38d
Revises: 93dd60cd2374
Create Date: 2026-01-07 14:41:46.758862

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bae863d9d38d"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "93dd60cd2374"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macd_filter_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("fast_period", sa.Integer(), nullable=False),
        sa.Column("slow_period", sa.Integer(), nullable=False),
        sa.Column("signal_period", sa.Integer(), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", name="uq_macd_filter_configs_strategy_id"),
    )
    op.create_index(
        op.f("ix_macd_filter_configs_strategy_id"),
        "macd_filter_configs",
        ["strategy_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_macd_filter_configs_strategy_id"), table_name="macd_filter_configs")
    op.drop_table("macd_filter_configs")
    # ### end Alembic commands ###
