"""add dynamic tp fields to trading_configs

Revision ID: f37c2c48dcb0
Revises: 8e4fcd3c3a40
Create Date: 2026-01-02 12:30:57.255612

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f37c2c48dcb0"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "8e4fcd3c3a40"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trading_configs", sa.Column("tp_dynamic_enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "trading_configs",
        sa.Column("tp_base_percent", sa.Numeric(precision=5, scale=2), nullable=False),
    )
    op.add_column(
        "trading_configs",
        sa.Column("tp_min_percent", sa.Numeric(precision=5, scale=2), nullable=False),
    )
    op.add_column(
        "trading_configs",
        sa.Column("tp_max_percent", sa.Numeric(precision=5, scale=2), nullable=False),
    )
    op.add_column(
        "trading_configs",
        sa.Column("tp_safety_margin", sa.Numeric(precision=5, scale=2), nullable=False),
    )
    op.add_column(
        "trading_configs", sa.Column("tp_check_interval_min", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trading_configs", "tp_check_interval_min")
    op.drop_column("trading_configs", "tp_safety_margin")
    op.drop_column("trading_configs", "tp_max_percent")
    op.drop_column("trading_configs", "tp_min_percent")
    op.drop_column("trading_configs", "tp_base_percent")
    op.drop_column("trading_configs", "tp_dynamic_enabled")
    # ### end Alembic commands ###
