"""initial_empty

Revision ID: f47dace14f65
Revises:
Create Date: 2025-12-29 15:11:05.216821

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f47dace14f65"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
