"""create trading_configs table

Revision ID: f7262dec4389
Revises: 90199c9f1c82
Create Date: 2026-01-01 21:06:05.612031

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7262dec4389"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "90199c9f1c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("order_size_usdt", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("margin_mode", sa.String(length=10), nullable=False),
        sa.Column("take_profit_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="uq_trading_config_account"),
    )
    op.create_index(
        op.f("ix_trading_configs_account_id"), "trading_configs", ["account_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trading_configs_account_id"), table_name="trading_configs")
    op.drop_table("trading_configs")
    # ### end Alembic commands ###
