"""create tp_adjustments table

Revision ID: fecd00227ca9
Revises: a162c33f6eea
Create Date: 2025-12-30 13:57:09.603589

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fecd00227ca9"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "a162c33f6eea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tp_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("old_tp_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("new_tp_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("old_tp_percent", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("new_tp_percent", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("funding_rate", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("funding_accumulated", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("hours_open", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("adjusted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tp_adjustments_adjusted_at", "tp_adjustments", ["adjusted_at"], unique=False
    )
    op.create_index("idx_tp_adjustments_trade_id", "tp_adjustments", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tp_adjustments_trade_id", table_name="tp_adjustments")
    op.drop_index("idx_tp_adjustments_adjusted_at", table_name="tp_adjustments")
    op.drop_table("tp_adjustments")
    # ### end Alembic commands ###
